#
# Version 2: Using VerneMQ, no conf file
#

version: '3.6'
services:
  mqtt:
    image: vernemq/vernemq:1.12.6.2
    container_name: vernemq
    restart: always
    ports:
      - '1883:1883'
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
    volumes:
      - vernemq_data:/var/lib/vernemq
  telegraf:
    image: telegraf:1.26.3-alpine
    container_name: telegraf
    restart: always
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mqtt
    links:
      - influxdb
    ports:
    - '8125:8125'
  influxdb:
    image: influxdb:2.7.1-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=brewhub
      - DOCKER_INFLUXDB_INIT_PASSWORD=brewhub78
      - DOCKER_INFLUXDB_INIT_ORG=brewhub
      - DOCKER_INFLUXDB_INIT_BUCKET=dockerism
      - DOCKER_INFLUXDB_INIT_RETENTION=365d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=12345678
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb2
volumes:
  grafana_data: {}
  influxdb_data: {}
  vernemq_data: {}
  