version: '3.6'
services:
  controller:
    image: brewhub.net/brewhub-controller:local-20230531-193434-amd64
    scale: 3
    restart: always
    environment:
      - MQTT__SERVER=mqtt
    depends_on:
      mqtt:
        condition: service_healthy
volumes:
  grafana_data: {}
  influxdb_data: {}
  vernemq_data: {}
  