version: '3.6'
services:
  influxdb:
    image: influxdb:2.7.1-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=brewhub
      - DOCKER_INFLUXDB_INIT_PASSWORD=brewhub78
      - DOCKER_INFLUXDB_INIT_ORG=brewhub
      - DOCKER_INFLUXDB_INIT_BUCKET=dockerism
      - DOCKER_INFLUXDB_INIT_RETENTION=365d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=12345678
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb2
  tempcontroller:
    image: brewhub.azurecr.io/tempcontroller:local-20230524-102615-amd64
    container_name: tempcontroller
    depends_on:
      - influxdb
    environment:
      - INFLUXDB__URL=http://influxdb:8086
      - INFLUXDB__TOKEN=12345678
      - INFLUXDB__ORG=brewhub
      - INFLUXDB__BUCKET=dockerism
    volumes:
    - ./config.toml:/config.toml:ro
  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

volumes:
  grafana_data: {}
  influxdb_data: {}