version: '3.6'
services:
  tempcontroller:
    image: brewhub.azurecr.io/tempcontroller:local-20230524-102615-amd64
    container_name: tempcontroller
    depends_on:
      - mqtt
    environment:
      - INFLUXDB__URL=http://influxdb:8086
      - INFLUXDB__TOKEN=12345678
      - INFLUXDB__ORG=brewhub
      - INFLUXDB__BUCKET=dockerism
    volumes:
    - ./config.toml:/config.toml:ro
  mqtt:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto
    restart: always
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  mqtt:
    image: vernemq/vernemq:1.12.6.2
    container_name: vernemq
    restart: always
    ports:
      - '1883:1883'
      - '8890:8890'
      - '8889:8889'
      - '8888:8888'
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
    volumes:
      - ./vernemq.conf:/etc/vernemq/vernemq.conf
      - vernemq_data:/var/lib/vernemq      
