version: '3.6'
services:
  controller:
    image: brewhub.net/brewhub-controller:local-20230601-102410-amd64
    deploy:
      replicas: 3
    restart: always
    environment:
      - MQTT__SERVER=mqtt
      - PROVISIONING__DOCKER=true
    depends_on:
      mqtt:
        condition: service_healthy
volumes:
  grafana_data: {}
  influxdb_data: {}
  vernemq_data: {}
  