{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Devices",
    "label": "Connected Devices",
    "query": "from(bucket: \"dockerism\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> keyValues(keyColumns: [\"device\"])\r\n|> group()\r\n|> keep(columns: [ \"_value\" ])\r\n|> distinct()\r\n"
   }
  ]
 },
 "panels": [
  { "title": "${Devices}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Devices" },
  {
   "title": "Reflux Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"dockerism\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device\"] == \"${Devices}\") \r\n  |> filter(fn: (r) => r[\"component\"] == \"rt\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"t\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Reflux Valve Open",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"dockerism\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device\"] == \"${Devices}\") \r\n  |> filter(fn: (r) => r[\"component\"] == \"rv\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"open\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Condenser Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"dockerism\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device\"] == \"${Devices}\") \r\n  |> filter(fn: (r) => r[\"component\"] == \"ct\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"t\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Condenser Valve Open",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"dockerism\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device\"] == \"${Devices}\") \r\n  |> filter(fn: (r) => r[\"component\"] == \"cv\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"open\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Ambient Temp Now",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dockerism\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device\"] == \"${Devices}\") \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dtmi:brewhub:sensors:TH;1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"t\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Device CPU Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dockerism\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device\"] == \"${Devices}\") \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dtmi:brewhub:prototypes:still_6_unit;1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"CpuLoad\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Ambient Temperature History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"dockerism\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device\"] == \"${Devices}\") \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dtmi:brewhub:sensors:TH;1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"t\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Ambient Humidity Now",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dockerism\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device\"] == \"${Devices}\") \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dtmi:brewhub:sensors:TH;1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"h\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Device Working Set",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dockerism\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device\"] == \"${Devices}\") \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dtmi:brewhub:prototypes:still_6_unit;1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"WorkingSet\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}